# Generated by Django 3.1.4 on 2021-01-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20200823_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='notes',
            field=models.TextField(default='nice'),
            preserve_default=False,
        ),
    ]
