# Generated by Django 3.1.4 on 2021-01-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
