# Generated by Django 3.0.8 on 2020-08-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='currency',
            field=models.CharField(default='KES - Kenyan Shilling', max_length=255),
        ),
    ]
